### ISSUE TITLE
PyOpenSci review - SLEPLET package

### ISSUE THREAD

**Issue by SimonMolinsky** [pmeier/pmeier#12]
Hi,

I've seen that you published the package `pystiche` for pyOpenSci. Maybe you'd be interested in reviewing another package? Or know someone who might be?

The package name is [SLEPLET](https://github.com/pyOpenSci/software-submission/issues/149):

```
SLEPLET is a Python package for the construction of Slepian wavelets in the spherical and manifold (via meshes) settings. SLEPLET handles any spherical region as well as the general manifold setting. The API is documented and easily extendible, designed in an object-orientated manner. Upon installation, SLEPLET comes with two command line interfaces - sphere and mesh - that allow one to easily generate plots on the sphere and a set of meshes using plotly. Whilst these scripts are the primary intended use, SLEPLET may be used directly to generate the Slepian coefficients in the spherical/manifold setting and use methods to convert these into real space for visualisation or other intended purposes. The construction of the sifting convolution was required to create Slepian wavelets. As a result, there are also many examples of functions on the sphere in harmonic space (rather than Slepian) that were used to demonstrate its effectiveness.
```

Would you be interested in the review? The process should be simplified because SLEPLET has been reviewed for JOSS. Documentation is in place and the package works without issues. It should take around a few hours max.

If you don't have time for this, maybe you know someone who might be interested in the review?

Thanks,
Szymon

**Comment by pmeier** [comment]
Hey @SimonMolinsky :wave: just dropping in to say that I saw your message. I'll only have time next week to get back to you with a proper answer.

**Comment by SimonMolinsky** [comment]
Hi Philip!

Thank you, and I am waiting for your decision :)

**Comment by pmeier** [comment]
@SimonMolinsky I took a look and I can't offer any domain knowledge. I'm familiar with 1D wavelets, but I don't have the time to read multiple research papers / a PhD thesis to get to know Slepian wavelets.

That being said, given that package was already accepted by JOSS, the domain part should already be reviewed. By submitting to PyOpenSci the author is probably looking for a review of the Python tools / good practices / ... That I can certainly offer.

If my assumption above is correct, I can act as reviewer. If you want that, feel free to ping me on the thread. I see that there are already two reviewers listed. Do you need a third one?

**Comment by SimonMolinsky** [comment]
Hi @pmeier

Yes, you are right. We need infrastructural / engineering / usability checks, not a validation of the implemented functions (I hoped these could potentially be used in your research).

Anyway, I would rather stick to two reviewers - who knows when pyOpenSci will need your help again? ;) I don't want to use your time in this situation :)

Once again - thank you for your willingness to help!

(I think you can close this thread. And one more thing - do you have a social media account where I can contact you in the future?)

**Comment by pmeier** [comment]
You can find me on [LinkedIn](https://www.linkedin.com/in/philip-meier-132739258/), but otherwise I don't use social media.
