### ISSUE TITLE
Regarding libjpeg-turbo support in torchvision

### ISSUE THREAD

**Issue by gurdeepmaurya** [pmeier/pmeier#6]
Hi Philip,

Could you please inform me if libjpeg-turbo has been integrated into torchvision? 
In case it is not, Are there plans to support it in torchvision in the next release?

Take Care

**Comment by pmeier** [comment]
Hey @gurdeepmaurya :wave:

It's complicated. We have pytorch/vision#6563 to track it. Unfortunately, there was no progress for the reasons listed in the issue. Our CI is a hodgepodge of different things at the moment. H1 of 2023 will see a huge push to clear this up, so after that is done, I think the chances are much higher to build against `libjpeg-turbo`. But for the next release, other than someone from the infra team taking interest in solving this, I don't see a chance of that happening.

**Comment by gurdeepmaurya** [comment]
Hmm. Well, I guess in the meantime we'll have to rely on PIL SIMD. Thanks for the clarification.
Take Care and Happy Holidays!!

**Comment by pmeier** [comment]
See pytorch/vision#7672
