### ISSUE TITLE
For ggold7046 only

### ISSUE THREAD

**Issue by ggold7046** [pmeier/pmeier#8]
Hi @pmeier , sorry for opening a new issue in here. As I was not able to comment on the previous issue. 

> unless you are contributing to a project that I'm working on

I see you work on Pytorch/vision. Can you guide me on any pytorch repo which would be easier for me? Or any repo you are working on where I can learn on the go ?

**Comment by pmeier** [comment]
> Can you guide me on any pytorch repo which would be easier for me?

There is no easy PyTorch repository. They are all quite complex. If I had to pick one for beginners in the ecosystem, it would be [`torchdata`](). However, note that this is not easy, but may be easier than the others.

> Or any repo you are working on where I can learn on the go ?

I currently don't work on other projects, sorry. I've outlined a few options for you to find a project to work on in https://github.com/pmeier/pmeier/issues/7#issuecomment-1378325501.

**Comment by ggold7046** [comment]
> There is no easy PyTorch repository. They are all quite complex.

I'm ready to learn what is necessary. I will put my effort. 

I couldn't find any torchdata repo.

**Comment by pmeier** [comment]
Programming is about solving problems. What did you do that lead to your conclusion 

> I couldn't find any torchdata repo.

?

**Comment by ggold7046** [comment]
Sorry, I could not understand your answer or question.

**Comment by pmeier** [comment]
What did you do that lead you to conclude that there is no torchdata repository? Did you look through the GH organization of PyTorch? Did you do a Google search? Basically, I'm asking: where did you look?

**Comment by ggold7046** [comment]
I looked at github pytorch main repo and searched for `torchdata` and couldn't find it. 

Are you talking about this repo [data](https://github.com/pytorch/data)  ?

out of the 3 good first issue in data repo ; 2 are taken and someone already is working on the 3rd issue.

**Comment by ggold7046** [comment]
Hi @pmeier , out of the 3 good first issue in data repo ; 2 are taken and  someone already is working on the 3rd issue.
